name: TheCore
main: com.comze_instancelabs.destroyerminigame.Main
version: 1.0
author: instancelabs
permissions:
  thecore.sign:
    description: Gives access to create signs for joining games.
commands:
   thecore:
      description: Main command
      usage: /thecore [name]
   tcadmin:
      description: Main command
      usage: /tcadmin [name]
   tc:
      description: Main command
      usage: /tc [name]
